---
- name: "System | {{ ansible_distribution }} | Update APT repos and upgrade APT packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "System | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name:
      - jq
    state: present
  become: true
